### ISSUE TITLE
Fanzine should be moved to Resources

### ISSUE THREAD

**Issue by s0r00t** [felipebueno/awesome-PICO-8#1]
They are "learning tools", with tutorials and such, but I think they shouldn't be in the same category as utilities such as PicoLove.

They should be in the Resources section. The fanzines are closer to the manual than to the external sprite editor.

**Comment by felipebueno** [comment]
@s0r00t thanks for catching that. I don't know why I put it there... I think I was sleepy 😅

I'll fix that asap

**Comment by felipebueno** [comment]
Oh, I forgot to hit Enter, that's why. It was in a hidden "Blogs, Magazines, etc" session.

But I think what you suggested makes more sense. Moved to Resources: https://github.com/felipebueno/awesome-PICO-8/commit/c7a0030098444f45e8be0676e17c590d37ea86ff
